name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 42 06 9 * *

jobs:
  build:
    name: Make build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build for AT90USB1286
      uses: ./.github/action-build
      with:
        mcu: at90usb1286
        arch: AVR8
        f-cpu: 16000000

    - name: Build for ATmega16U2
      uses: ./.github/action-build
      with:
        mcu: atmega16u2
        arch: AVR8
        f-cpu: 16000000

    - name: Build for ATmega32U4
      uses: ./.github/action-build
      with:
        mcu: atmega32u4
        arch: AVR8
        f-cpu: 16000000

    - name: Create release on GitHub (only on push)
      if: github.event_name == 'push'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: Latest build
        files: |
          .action_build_outputs/*
